name: Dart CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image:  dart:latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: dart pub get
    - name: Run tests
      run: dart pub run test --coverage="coverage"
    - name: Install coverage tools
      run: dart pub global activate coverage
    - name: format coverage
      run: $HOME/.pub-cache/bin/format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib
    - uses: codecov/codecov-action@v2
      with:
        files: coverage.lcov
        verbose: true # optional (default = false)

